name: Run tests then Deploy
on:
  push:
    branches:
      - main  # Corrected to the main branch; replace 'main' with your actual branch name
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test_assignment_14:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./Dockerfile.ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'Assignment_14'  # Assuming this is still the correct directory path

      - name: Build docker images
        run: docker build -t main -f $COMPOSE_FILE .
        working-directory: ./Assignment_14

      - name: Run tests
        run: docker run main
        working-directory: ./Assignment_14

  deploy:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: test_assignment_14
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      BUILD_PATH_PREFIX: ${{ github.event.repository.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: echo $BUILD_PATH_PREFIX
      - name: Build the project
        run: npm run build  # Assuming 'npm run build' is the correct command; 'npm run cd' seems incorrect
        working-directory: ./Assignment_14

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Assignment_14/dist'

      - name
