name: Run Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        run: make build
        working-directory: ./Assignment13


  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./Assignment13/Dockerfile.ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker build -t main -f $COMPOSE_FILE .

      - name: Run tests
        run: docker run main
