name: Run Tests

on:
  push:

jobs:

  test:
    needs: build
    runs-on: ubuntu-latest
    working-directory: ./Assignment_13
    env:
      COMPOSE_FILE: ./Dockerfile.ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker build -t main -f $COMPOSE_FILE .

      - name: Run tests
        run: docker run main
